---

- hosts: 192.168.1.31
  become: true
  tasks:
    
    - name: install apache2 package + php support for Ubuntu
      package:                      # "package" is normore generic than "apt": generic OS package manager 
        name: 
          - "{{ apache_package }}"  # Variable added, see inventory file
          - "{{ php_package }}"     # Variable added, see inventory file  
        state: latest 
        update_cache: yes 
      when: ansible_distribution in ["Debian", "Ubuntu"] and ansible_userspace_architecture in ["x86_64"]    

