---

- hosts: all
  become: true
  pre_tasks:
    
    - name: install updates (Ubuntu)
      tags: always
      package:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    
    - name: install updates (CentOS)
      tags: always
      package:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"


        # - hosts: all
        # become: true
        # roles:
        # - base


- hosts: ansible                                # add the User "Simone" to every Host, Prereq. for full Ansible automation
  become: true
  roles:
    - ansible


- hosts: workstations
  become: true
  roles:
    - workstations


- hosts: proxmox
  become: true
  roles:
    - proxmox

    
- hosts: web_server                 # see "inventory" file             192.168.1.31 only
  become: true
  roles:
    - web_servers


- hosts: db_server                 # see "inventory" file             192.168.1.32 / 33 only
  become: true
  roles:
    - db_servers


- hosts: file_server                 # see "inventory" file             192.168.1.34 / 35 only
  become: true
  roles:
    - file_servers


